sailfishos/connman

- connman/src/service.c
The timer was made to trigger autoconnect round for services that are
in failed state. However, the cellular service does not stay in the failed
state for long and goes idle right after the timer is started due to
gofono's "activate-failed" signal being triggered.
This PR includes two commits: the first makes autoconnect round to start
regardless the service is in idle state, and the second does not allow auto
connection bypassing the back off timer.
> [service] Do not start autoconnect round without a back-off timer. JB#52947

- connman/plugins/vpn.c
- connman/src/systemd_login.c
This change adds handling of `ENODATA` as an error that does not result in quitting the periodic process of checking active user. This may happen when systemd has not yet got the complete data (e.g., `ACTIVE_UID` is missing from the seat).
> Handle ENODATA in systemd login monitor.

- connman/vpn/plugins/l2tp.c
- connman/vpn/plugins/openfortivpn.c
- connman/vpn/plugins/pptp.c
[l2tp] Improve invalid auth and disconnect notify, fix cb use. JB#52482
[pptp] Improve invalid auth and disconnect notify, fix cb use. JB#52482
[openfortivpn] Improve invalid auth and disconnect notify, fix cb use. JB#52482
All follow the same codebase, same fixes apply to all. This fixes issue of VPN not dying in case the auth is invalid.
These changes enforce quitting of the VPN plugin when it is being disconnected, also because of invalid authentication and then prompts for new password via VPN agent. These fix premature calling of the connect callback before connection status is being evaluated at all. Other minor cleanups and fixes here and there.
Slight increase in memory consumption because of storing the private variables for the duration of the connection. It seems that these …
> Improve invalid auth and disconnect notify, fix cb use in PPPD based VPN plugins

- connman/doc/vpn-connection-api.txt
- connman/plugins/vpn.c
- connman/vpn/plugins/openvpn.c
- connman/vpn/vpn-provider.c
- connman/vpn/vpn-provider.h
Implement heuristic for auth error counter to avoid losing credentials because of misbehaving server reporting back `AUTH_FAILED` control message. This is achieved by adding "`AuthErrorLimit`" that can be set by user via D-Bus or by a VPN plugin. By default one (1) auth error is allowed until credentials are re-requested (or cleared by the VPN agent). OpenVPN sets this value by default to 10 unless already defined and can be disabled by setting value zero (0). Some VPNs may not require this option and that is why lenience of one such error is allowed by default. This feature is included only when the previous connection with the provider has been successful but there are authentication errors reported as a result of server denying the connection by some specific reason. This does not …
> Implement auth error heuristic and per provider value

- connman/gdhcp/client.c
- connman/gdhcp/common.c
- connman/gdhcp/common.h
- connman/include/network.h
- connman/plugins/sailfish_ofono.c
- connman/src/connman.h
- connman/src/ipconfig.c
- connman/src/network.c
Might not be the optimal solution but this resolves the issue. By adding an additional check to not to change the ipconfig method unnecessarily and not allowing to update modem ipconfiguration when disconnecting the issue seems to go away. Nevertheless, it was wrong to change ipconfig method from what ofono informed it to be. Utilizing the disconnecting check ensures that settings file is not updated with invalid information.
In addition to this a delayed connect for the cellular is implemented. This will ensure that all IP families do have proper configuration set. The checks apply only to FIXED and MANUAL mode configurations which do need to have local address set by ofono and informed to connmand. Otherwise in some bootup cases there will be two IPv4 addresses for the interface as the …
> Fix IPv4 not working properly on dual mode cellular

- connman/doc/connman.conf.5.in
- connman/src/main.c
Change connmand behavior to utilize different permissions for the StorageRoot creation if it does not exist to allow other users to view the contents as well. The subdirectories `connman` and `connman-vpn` are created using stricter permissions (root only). Default to 755 permissions with StorageRoot.
Document the StorageRoot related permissions into conf man page.
> Create StorageRoot with 755 if it does not exist and document options.

- connman/src/connman.service.in
- connman/src/main.c
- rpm/connman.spec
Follow [upstream](https://git.kernel.org/pub/scm/network/connman/connman.git/tree/src/connman.service.in) in `connman.service.in`. This changes the type to dbus, which according to `systemd-analyze` cuts the initialization time to ~1/10. Take also other changes upstream has had for systemd for long time.
Remove the symlink from `network.target.wants`. This was wrong as network.target did wait for connmand to complete causing unnecessary delays. This must be done other way around as upstream service file has, and is recommended by [systemd documentation](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/) and thus, the symlink(s) are moved to `multi-user.target.wants`.
> Update and fix ConnMan systemd rules

- connman/plugins/ethernet.c
- connman/src/service.c
This change fixes the re-insertion of a hot-plug USB ethernet. The index of the interface was not updated so after re-insertion the old index was used which resulted in DHCP failing to start. Also included one fix from upstream for ethernet.
> Fix USB ethernet hot-plug

- connman/src/ipconfig.c
This is a patch proposed to upstream. And this is indeed an issue, since the USB device is already removed prior processing this bits in ifconfig.c -> IPv6 gets disabled. This was an unseen and surprising side effect of how USB devices are reacted to.
> [ipconfig] Do not enable/disable ipv6 for all ifs. Fixes JB#56478

- connman/include/agent.h
- connman/src/agent-connman.c
- connman/src/agent.c
- connman/src/connman.h
- connman/src/service.c
Hidden services do not keep the pending call when connecting as that is
forwarded for agent to handle, if present. This patch set adds simple search
to agent.c that can be used in service.c via agent-connman.c to check if the
hidden service has a pending connect request.
It was noticed that two consecutive connect requests for a hidden service was
possible and this resulted in adding two separate requests when agent was
present. First requests was placed as the pending request on the agent and the
second one was allowed as well but it was put into the queue. And when time-out
happened on the first one then the duplicate request would have been sent.
UI components relying on D-Bus API should not have to deal with this, it is
better to handle this case on ConnMan side.
> Check for pending requests also on hidden WiFi networks

- connman/Makefile.am
- connman/Makefile.plugins
- connman/unit/test-vpn-util.c
- connman/vpn/plugins/vpnc.c
- connman/vpn/vpn-util.c
- rpm/connman.spec
Move resolv.conf to /run/connman/resolv.conf to make resolver configuration available inside sailjail
> Move resolv.conf to /run/connman/resolv.conf

- connman/src/detect.c
- connman/src/device.c
- connman/src/ipconfig.c
- connman/src/network.c
- connman/src/ntp.c
- connman/src/rtnl.c
Applied a patch that fixes the alignment of netlink messages. And also couple of others non-related to maintain consistency in rtnl.c.
Reverted old debug disable commit that was not just proper. `DBG()`s are handled via bootup option or D-Bus toggle with dbuslog-tools.
> [connman] Apply upstream rtnl patches, revert debug disable commit. JB#57933

- connman/gweb/gweb.c
- connman/src/wispr.c
[connman] Synchronize wispr from upstream. JB#59298
This set of commits mainly addresses the CVE-2022-32293. In addition many
other related commits are taken from upstream to avoid diverging even more
than this currently is. This brings wispr.c closer to the upstream version.
Commits directly fixing CVE-2022-32293:
8f66eb5d94d6d27126cada3566363f4ba3f987b5 
7f7176b8db269cae7cd66b003bb7d6c38340f6a8
2a3f816bd188735feead63b9f68c54afef1ffe89
> [connman] Address CVE-2022-32293. Fixes JB#59298

- connman/gweb/gweb.c
- connman/src/main.c
Applies an upstream patch: "gweb: Fix crash on malformed http response" 
[22901212105055b24f73504a74f5a57eee809777](https://git.kernel.org/pub/scm/network/connman/connman.git/commit/gweb/gweb.c?id=22901212105055b24f73504a74f5a57eee809777)
to address issue caused by a CVE-fix "gweb: Fix OOB write in received_data()"
[d1a5ede5d255bde8ef707f8441b997563b9312bd](https://git.kernel.org/pub/scm/network/connman/connman.git/commit/gweb/gweb.c?id=d1a5ede5d255bde8ef707f8441b997563b9312bd).
Also drop the use of errors for reading IPv4 status url from the configuration file. With
IPv6 this was also ignored and the default is being returned when the status url is not
set. This caused a Glib warning as GError was not cleared.
> [connman] Apply upstream fix for HTTP response crash. Fixes JB#59564

- connman/doc/vpn-connection-api.txt
- connman/doc/vpn-overview.txt
- connman/include/provider.h
- connman/plugins/vpn.c
- connman/src/agent.c
- connman/src/connman.h
- connman/src/provider.c
- connman/src/service.c
- connman/vpn/plugins/vpn.c
- connman/vpn/plugins/vpn.h
- connman/vpn/vpn-agent.c
- connman/vpn/vpn-provider.c
- connman/vpn/vpn-provider.h
This fixes the VPN dialog timeout happening too early. The cause for it was
that connmand did connection timeout for every type of service after 120s
interval. The configuration value InputRequestTimeout for vpnd in
connman-vpn.conf was not, therefore, followed and the setting had no effect.
In order to fix the issue VPN connections now have association state in which
the connection timeout of connmand is not in effect. This state is the new
initial state for VPN connections to which they enter after getting connect
request. In this state VPNs request the credentials of sorts from the VPN
agent, which in turn requests missing content from user. The input request
timeout set in the settings is therefore followed as the VPN is not really yet
connected to the server and is not subject to …
> [vpn] Add association state to fix dialog timeout issue. Fixes JB#59447

- connman/plugins/sailfish_ofono.c
It seems that in some cases with VoLTE the too short wait for IPv4 connection information from the operator may be the cause for not having IPv4 connectivity at all. This fix was done previously to address certain error situations with some operators and the limit was set to 2 seconds, it might be that with VoLTE we need longer wait for the IPv4 information in dual mode.
> [ofono] Increase delayed connect wait to 5 seconds. JB#58538 JB#59714

- connman/src/connman.h
- connman/src/device.c
- connman/src/technology.c
- connman/src/timezone.c
- connman/unit/test-device.c
The devices, let alone technologies are not loaded nor set up yet when timezone
reads the current time and attempts to set up regulatory domain. This change
fixes the issue by saving the regulatory domain as a global for the
technologies which is then used by the device during power up.
> [connman] Apply regdom changes to powering up devices. Fixes JB#55556

- connman/plugins/sailfish_ofono.c
This reverts commit 6b6e680c7df9a8c999a533c83ac89e9c5ccf933a.
The change did not solve any issue it was assumed to fix. It just made connection establishment with troublesome networks being much more slower, for the 5 second period set here.
> [ofono] Revert "Increase delayed connect wait to 5 seconds". JB#59714

- connman/gdhcp/client.c
- connman/src/peer.c
- connman/tools/stats-tool.c
- connman/unit/test-globalproxy.c
- connman/unit/test-storage.c
Fix the warnings 64bit arch build gives. Also replace deprecated g_memdup() with the new g_memdup2().
> [connman] Fix 64bit arch build warnings and deprecated func. Fixes JB#54603

- connman/plugins/sailfish_ofono.c
- connman/src/connection.c
- connman/src/dnsproxy.c
This contains mostly cleanups and minor fixes to interface index use after the CLAT VPN changes introduced big changes on the behavior by supporting separate interfaces per service.
- It is not necessary to get the indexes from the ipconfig in connection.c. Use the ones set in data directly to be more consistent.
- In ofono plugin avoid updating network index with invalid 
- In dnsproxy check both IPv{4,6} indexes when service state changes.
> [connman] Cleanup and fix index uses after CLAT VPN changes. Fixes JB#60897

- rpm/connman.spec
We have done multiple stop releases since this cleanup script was introduced. Thus, this can be safely removed.
See 3.0.2 release / sha1 cea1f1fd21b8b70dd70
> [connman] Cleanup post-install script. Fixes JB#60966

- connman/src/connman.h
- connman/src/storage.c
- connman/vpn/vpn-provider.c
On some devices, mostly older ones this was an issue that came out of nowhere that VPN providers were not saved when created or modified. No real idea what caused it because on new, such as Xperia 10 III this worked.
With the changes here at least X10 I got saving working again. Cleanup of code was also made in addition to increasing logging and error reporting.
> Fix saving of  VPN provider in some cases.

- connman/src/timezone.c
Patch from upstream:
Add missing code for handling an empty subpath.
> [timezone] Fix handling of empty subpath in find_origin(). JB#61335

- connman/src/service.c
Send the PropertyChanged signal with key DefaultService when changing the default service. Use the path of the service as value for the key. This is done in order to make the default service status changes explicit for higher layers to interpret.
> Signal DefaultService prop if default service changed.

- connman/src/inet.c
Apply upstream fix to set correct attribute type for RTA_DST.
> [inet] Append correct attribute type for RTA_DST. Fixes JB#60963

- connman/src/dhcpv6.c
- connman/src/inet.c
- connman/src/ipaddress.c
- connman/src/iptables.c
This syncs inet.c a bit closer to upstream by applying:
- Prefixlen for adding a route
- Support for subnet routes in
- Fix return value tests for inet_pton
> Upstream fixes: prefixlen for routes, support subnet routes, fix inet_pton retval tests

- connman/vpn/connman-vpn.service.in
- connman/vpn/main.c
Support multiple `-d` options at startup, implementation is the same as in connmand. Also read startup options similarly to connmand as the service starts.
> Enhance connman-vpnd debug use

- connman/vpn/plugins/openvpn.c
This can be apparently used with --cipher option so no need to complicate with checks that which to use.
> Support --data-ciphers option in OpenVPN plugin

- connman/doc/vpn-config-format.txt
Add DataCiphers and DataCiphersFallback to OpenVPN documentation. Add note about Cipher being replaced in 2.6.
> Update OpenVPN cipher options documentation.

- connman/vpn/plugins/openfortivpn.c
This fixes crash when connecting to a server with invalid credentials. vpn.c:vpn_died() expects a pointer to the provider when called.
> Use provider as parameter for vpn_died() in OpenFortiVPN

- connman/plugins/sailfish_wifi.c
- connman/src/network.c
This will reduce at least debug noise but makes the calculation to be only once before it is needed.
> Calculate WiFi weak RSSI before lists are processed, remove network dbg

- connman/src/rtnl.c
Change the warning to DBG.
Apply upstream change for interface ignore in rtnl.
> Remove noisy warning, ignore interfaces added to/del from bridge

- connman/vpn/plugins/vpn.c
- connman/vpn/plugins/wireguard.c
This makes it possible to keep the errors visible in UI in both configuration and parameter failures. Also UI now can see all state transformations, and is a bit better responsive when the endpoint cannot be resolved after connection to it is established (a configuration error leading to completely unresponsive VPN UI).
Also other cleanups and fixes documented in the commit messages.
> Fix WireGuard VPN plugin behavior in error cases

- connman/Makefile.am
- connman/gweb/gresolv.c
- connman/gweb/gresolv.h
- connman/vpn/plugins/wireguard.c
- connman/vpn/vpn-util.c
- connman/vpn/vpn.h
In order to avoid blocking vpnd when network is not properly connected do the DNS reresolve with GResolve first, `getaddrinfo()` later.
> Use GResolv for DNS reresolve in WireGuard VPN plugin

- connman/vpn/plugins/vpn.c
- connman/vpn/plugins/wireguard.c
The shutdown process needs vpn_died() to be called to complete the cycle. Do this as if simulating a VPN with daemon.
Tell that WireGuard uses no agent to complete the state machine and to not to change state in vpn.c. It was wrong, vpn-provider.c handles state transition when -EINPROGRESS is received to connect request.
Fix also one possible call made to nonexistent function.
> [wireguard] Fix shutdown process and no-daemon VPN state machine. Fixes JB#62314

- connman/Makefile.am
- connman/include/provider.h
- connman/plugins/vpn.c
- connman/src/provider.c
- connman/src/shared/util.c
- connman/src/shared/util.h
- connman/unit/test-service.c
- connman/vpn/plugins/wireguard.c
- connman/vpn/vpn-provider.c
This adds support for having both IPv4 and IPv6 on VPNs. Traditionally VPNs have been either or but WireGuard can utilize both.
Use a simple way of having the IP family types in an boolean array to avoid rewriting whole VPN implementation to match the other services. That work is to be done later.
> Support dual IP addresses on VPNs

- connman/src/inet.c
- connman/vpn/plugins/wireguard.c
- connman/vpn/vpn-provider.c
- connman/vpn/vpn-provider.h
With WireGuard split routing option is to be overridden as the AllowedIPs define the IP ranges that can be used according to the cryptokey routing table set on the server. Therefore, the split routing option is set only when there are no "any" routes defined.
This also contains changes to add routes to the IP networks defined with AllowedIPs. For now, the routes are added only based on the IP family of the current endpoint. The routes are removed and re-added if the endpoint resolves to another address, and in such case it is done without a delay. Normally, at startup, there is a 200ms delay.
Also took one upstream commit on preventing to add invalid routes to routing table. Might be useful in some cases, maybe even here.
> Split routing and route setup changes for WireGuard

- connman/src/connman.h
- connman/src/main.c
- connman/src/setting.c
The additional configs may have a small amount of keys, it is more optimal to read only what are set. Furthermore, this avoids from resetting values to default which have a default value, like a string list for blacklisted interfaces, when additional config is read by going through all the values.
> Read only keys that exist from conf.d configs.

- connman/gdbus/watch.c
- connman/gweb/gresolv.c
- connman/gweb/gweb.c
- connman/plugins/vpn.c
- connman/src/dhcpv6.c
- connman/src/firewall-iptables.c
- connman/src/ipconfig.c
- connman/src/storage.c
- connman/src/technology.c
- connman/vpn/plugins/openvpn.c
- connman/vpn/plugins/vpn.c
These fixes are for some Clang analyzer findings. There are still more, some false positives and relying on memory allocation failing or does not understand the unref-approach used in many places, but these are most obvious ones for now.
> Fix some Clang analyzer findings

- connman/src/inet.c
- connman/src/service.c
- connman/vpn/plugins/vpn.c
- connman/vpn/plugins/wireguard.c
- connman/vpn/vpn-provider.c
- connman/vpn/vpn-provider.h
Changing network on certain devices seemed to make WireGuard quit connecting or looping quite a lot between connect->disconnect->idle->connect. These fixes address the problem of premature quitting in case the results from `getaddinfo()` cannot be connected yet by simply returning a non-terminal EHOSTUNREACH so WireGuard is attempted again with VPN autoconnect.
The connect-disconnect loop can be elimintated by increasing the delay of calling `wg_died()` when WireGuard is being disconnected. This could otherwise, with the 1ms delay, cause quite interesting behavior of connmand not having enough time to setup the routes as the interface disappears too fast because of some network condition not being set, which will then result in many attempts of connect and disconnect and having trouble in …
> Make WireGuard to work better with network changes

- connman/src/provider.c
- connman/src/shared/util.h
- connman/vpn/plugins/wireguard.c
This fixes the issue that WireGuard would not work if the endpoint (hostname) is a FQDN. The main cause was that the FQDN name was used as a gateway when adding routes, which is now using the resolved IP.
Also the code has changes to handle the initial resolve and the reresolve of the  endpoint differently. In the first case it utilizes `getaddrinfo()` to do the resolve but in the latter case GResolv does the resolving and the results do not need to be resolved again, just to fill the strutures with `getaddrinfo()` with `AI_NUMERICHOST`.
Changed also to start the DNS reresolve only when there is a FQDN defined as entpoint.
> Fix WireGuard FQDN hostname resolving

- connman/src/dns-systemd-resolved.c
This fixes the leaking of DNS requests outside VPN with systemd-resolved. Only the online service's DNS are used, and the default one is set as the default DNS route link in resolved too, and disconnected are reverted to original state so they are not used. But most importantly, VPNs do not leak the queries outside.
> Fix VPN DNS leaks with systemd-resolved

- connman/doc/connman.conf.5.in
- connman/include/setting.h
- connman/src/service.c
- connman/src/setting.c
Add option to settings to define a default value for mDNS and document it.
Since the "false" mDNS value is dropped from the service file, so there is no knowledge if the user has disabled it explicitly and that is why the value is set only for new services. Otherwise each load of the service would set the system override for old services, from which mDNS was disabled - assuming system setting is "true".
Adding only to Ethernet and WLAN for now.
This has changes from the other PRs https://github.com/sailfishos/connman/pull/100 and https://github.com/sailfishos/connman/pull/101 included to ease testing.
> Add option for setting default mDNS value for all new Ethernet/WLAN services

- rpm/connman.spec
In updates it is better to use -h than -s for checking that the link exists.
> Check if resolv.conf is a symlink instead of size in remove.

- connman/include/setting.h
- connman/src/setting.c
- connman/src/tethering.c
Add a configuration option to enable mDNS for the tethering network.
> Support setting mDNS on the tethering network

- connman/src/dnsproxy.c
Apply upstream fix for CVE-2025-32366 to dnsproxy.c.
Now that we use resolved this does not apply to us, and the `parse_rr` is only on the cache side of  `dnsproxy.c` so it does not affect the `shared/dns.c`.
> [dnsproxy] Address CVE-2025-32366 vulnerability. Fixes JB#63369
